version: "3"

services:
  caloriesmanagement:
    image: javaprojects/caloriesmanagement
    networks:
      - caloriesmanagement-network
    ports:
      - 80:8080
    depends_on:
      - caloriesmanagement-database

  caloriesmanagement-database:
    image: javaprojects/caloriesmanagement-db
    volumes:
      - "caloriesmanagementdata:/var/lib/postgresql/data"
    networks:
      - caloriesmanagement-network
    ports:
      - 5555:5432

networks:
  caloriesmanagement-network:

volumes:
  caloriesmanagementdata: